# K-Gateway Integration Resources
# Static Backend + HTTPRoute + TrafficPolicy for authentication bypass
#
# IMPORTANT: Update the parentRefs.name and namespace to match your gateway
# IMPORTANT: Update the gateway hostname in the comments below
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: weather-static-backend
  namespace: ai-services
  labels:
    app: weather-mcp
    backend-type: static
spec:
  type: Static
  static:
    hosts:
      - host: weather-mcp.ai-services.svc.cluster.local
        port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: weather-service-route
  namespace: ai-services
  labels:
    app: weather-mcp
    route-type: weather-service
spec:
  parentRefs:
  # CUSTOMIZE: Update to match your gateway name and namespace
  - name: agentgateway
    namespace: kgateway-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /weather-service
      backendRefs:
        - group: gateway.kgateway.dev
          kind: Backend
          name: weather-static-backend
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /

---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: disable-weather-service-auth
  namespace: ai-services
  labels:
    app: weather-mcp
    policy-type: service-auth-disable
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: weather-service-route
  extAuth:
    disable: {}
  rbac:
    action: Allow
    policy:
      matchExpressions:
      - "true"