---
# Weather Dynamic MCP Server Cleanup Playbook
# 
# This playbook removes weather Dynamic MCP resources deployed by deploy-weather-mcp-dynamic.yml
# Specifically handles:
# - Dynamic MCP Backend with label selectors
# - Services with appProtocol: kgateway.dev/mcp
# - StreamableHTTP transport configuration
# - Selector-based service discovery
# 
# Useful for:
# - Development iterations with Dynamic MCP
# - Testing different Dynamic MCP configurations
# - Troubleshooting Dynamic MCP deployment issues
# - Switching from Dynamic back to Static MCP
# - Complete Dynamic MCP environment reset
#
# Prerequisites:
# - Kubernetes cluster access
# - kubectl configured with appropriate permissions
# - Same kubeconfig used for Dynamic MCP deployment
#
# Usage:
#   ansible-playbook cleanup-weather-mcp-dynamic.yml
#   ansible-playbook cleanup-weather-mcp-dynamic.yml --extra-vars "force_cleanup=true"
#
- name: Cleanup Weather Dynamic MCP Server Resources
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../../group_vars/all.yml
  vars:
    kubeconfig_path: "{{ playbook_dir }}/../../../kubeconfig"
    kubectl_cmd: "kubectl --kubeconfig={{ kubeconfig_path }}"
    ai_namespace: "ai-services"
    kgateway_namespace: "kgateway-system"
    
    # Dynamic MCP service configuration (must match deployment)
    service_name: "weather-mcp-dynamic"
    
    # Cleanup confirmation (can be overridden with --extra-vars "force_cleanup=true")
    force_cleanup: false

  tasks:
    # Phase 0: Prerequisites and Confirmation
    - name: Check if kubeconfig exists
      stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_file

    - name: Fail if kubeconfig doesn't exist
      fail:
        msg: "Kubeconfig file not found at {{ kubeconfig_path }}"
      when: not kubeconfig_file.stat.exists

    - name: Confirm cleanup operation
      pause:
        prompt: |
          
          ⚠️  WARNING: This will remove the following Weather Dynamic MCP resources ⚠️
          
          Resources to be deleted (Dynamic MCP with label selectors):
          - TrafficPolicy: {{ service_name }}-no-auth
          - HTTPRoute: {{ service_name }}-route
          - Backend: {{ service_name }}-backend (Dynamic MCP with selectors)
          - Service: {{ service_name }} (with appProtocol: kgateway.dev/mcp)
          - Deployment: {{ service_name }}
          
          Namespace: {{ ai_namespace }}
          Service Type: Dynamic MCP (label selector-based)
          Transport: StreamableHTTP
          
          Continue with cleanup? (yes/no)
      register: cleanup_confirmation
      when: not (force_cleanup | default(false) | bool)

    - name: Check cleanup confirmation
      fail:
        msg: "Cleanup operation cancelled by user"
      when: 
        - not (force_cleanup | default(false) | bool)
        - cleanup_confirmation.user_input | lower not in ['yes', 'y']

    # Phase 1: Remove TrafficPolicy (must be removed before HTTPRoute)
    - name: Remove Dynamic MCP TrafficPolicy
      kubernetes.core.k8s:
        api_version: gateway.kgateway.dev/v1alpha1
        kind: TrafficPolicy
        name: "{{ service_name }}-no-auth"
        namespace: "{{ ai_namespace }}"
        state: absent
        kubeconfig: "{{ kubeconfig_path }}"
        wait: true
        wait_timeout: 30
      ignore_errors: true

    # Phase 2: Remove HTTPRoute
    - name: Remove Dynamic MCP HTTPRoute
      kubernetes.core.k8s:
        api_version: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        name: "{{ service_name }}-route"
        namespace: "{{ ai_namespace }}"
        state: absent
        kubeconfig: "{{ kubeconfig_path }}"
        wait: true
        wait_timeout: 30
      ignore_errors: true

    # Phase 3: Remove Dynamic MCP Backend (with label selectors)
    - name: Remove Dynamic MCP Backend
      kubernetes.core.k8s:
        api_version: gateway.kgateway.dev/v1alpha1
        kind: Backend
        name: "{{ service_name }}-backend"
        namespace: "{{ ai_namespace }}"
        state: absent
        kubeconfig: "{{ kubeconfig_path }}"
        wait: true
        wait_timeout: 30
      ignore_errors: true

    # Phase 4: Remove Service (with MCP protocol annotations)
    - name: Remove Dynamic MCP Service
      kubernetes.core.k8s:
        api_version: v1
        kind: Service
        name: "{{ service_name }}"
        namespace: "{{ ai_namespace }}"
        state: absent
        kubeconfig: "{{ kubeconfig_path }}"
        wait: true
        wait_timeout: 60
      ignore_errors: true

    # Phase 5: Remove Deployment
    - name: Remove Weather Dynamic MCP Deployment
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        name: "{{ service_name }}"
        namespace: "{{ ai_namespace }}"
        state: absent
        kubeconfig: "{{ kubeconfig_path }}"
        wait: true
        wait_timeout: 120
      ignore_errors: true

    # Phase 6: Verify cleanup completion
    - name: Wait for pods to be terminated
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ ai_namespace }}"
        label_selectors:
          - "app={{ service_name }}"
        kubeconfig: "{{ kubeconfig_path }}"
      register: remaining_pods
      until: remaining_pods.resources | length == 0
      retries: 12
      delay: 5
      ignore_errors: true

    # Phase 7: Final verification and cleanup report
    - name: Check for remaining Dynamic MCP resources
      kubernetes.core.k8s_info:
        api_version: "{{ item.api_version }}"
        kind: "{{ item.kind }}"
        namespace: "{{ ai_namespace }}"
        kubeconfig: "{{ kubeconfig_path }}"
      register: remaining_resources
      loop:
        - api_version: apps/v1
          kind: Deployment
        - api_version: v1
          kind: Service
        - api_version: gateway.networking.k8s.io/v1
          kind: HTTPRoute
        - api_version: gateway.kgateway.dev/v1alpha1
          kind: TrafficPolicy
        - api_version: gateway.kgateway.dev/v1alpha1
          kind: Backend

    - name: Filter Dynamic MCP related resources
      set_fact:
        dynamic_mcp_resources: >-
          {%- set resources = [] -%}
          {%- for result in remaining_resources.results -%}
            {%- for resource in result.resources -%}
              {%- if service_name in resource.metadata.name -%}
                {%- set _ = resources.append({
                  'kind': result.item.kind,
                  'name': resource.metadata.name,
                  'namespace': resource.metadata.namespace
                }) -%}
              {%- endif -%}
            {%- endfor -%}
          {%- endfor -%}
          {{ resources | to_json }}

    # Phase 8: Display cleanup summary
    - name: Display cleanup summary
      debug:
        msg: |
          
          ============ Weather Dynamic MCP Cleanup Complete ============
          
          {% set parsed_resources = dynamic_mcp_resources | from_json if dynamic_mcp_resources is string else dynamic_mcp_resources %}
          {% if parsed_resources | length == 0 %}
          ✅ CLEANUP SUCCESSFUL - All Dynamic MCP resources removed
          {% else %}
          ⚠️  CLEANUP INCOMPLETE - Remaining resources found
          {% for resource in parsed_resources %}
          - {{ resource.kind }}/{{ resource.name }}
          {% endfor %}
          {% endif %}
          
          Resources Processed:
          ✅ TrafficPolicy: {{ service_name }}-no-auth
          ✅ HTTPRoute: {{ service_name }}-route
          ✅ Backend: {{ service_name }}-backend (Dynamic MCP, label selectors)
          ✅ Service: {{ service_name }} (appProtocol: kgateway.dev/mcp)
          ✅ Deployment: {{ service_name }}
          
          Service Details:
          📦 Service Name: {{ service_name }}
          🎯 Service Type: Dynamic MCP (label selector-based)
          🌐 Namespace: {{ ai_namespace }}
          🚀 Transport: StreamableHTTP
          🔧 Cleanup Mode: {{ 'Forced' if (force_cleanup | default(false) | bool) else 'Interactive' }}
          
          {% if parsed_resources | length == 0 %}
          🎉 Dynamic MCP environment is clean and ready for fresh deployment!
          
          Next steps:
          1. Run: ansible-playbook deploy-weather-mcp-dynamic.yml
          2. Or deploy Static MCP: ansible-playbook deploy-weather-mcp-only.yml
          3. Or modify Dynamic MCP configuration and redeploy
          {% else %}
          ⚠️  Manual cleanup may be required for remaining resources.
          
          Check manually:
          kubectl get all,httproutes,trafficpolicies,backends -n {{ ai_namespace }} | grep {{ service_name }}
          {% endif %}
          
          =======================================================================